# Generated by Django 4.1.7 on 2023-03-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/payments/'),
        ),
    ]
