# Generated by Django 4.1.7 on 2023-03-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_machine_machine_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/suppliers/machines/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/suppliers/products/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='logo_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/suppliers/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='marketing_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/suppliers/'),
        ),
    ]
