# Generated by Django 4.1.7 on 2023-03-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partspage',
            name='marketing_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/spareparts/'),
        ),
        migrations.AlterField(
            model_name='supplierpage',
            name='logo_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/spareparts/'),
        ),
    ]
