# Generated by Django 4.1.7 on 2023-03-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0002_alter_partspage_marketing_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partspage',
            name='marketing_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='spareparts/'),
        ),
        migrations.AlterField(
            model_name='supplierpage',
            name='logo_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='spareparts/'),
        ),
    ]
