# Generated by Django 4.1.7 on 2023-03-22 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='image',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='images/displays/specials', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
        migrations.AlterField(
            model_name='stat',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/displays/stats', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
