# Generated by Django 4.1.7 on 2023-03-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_terms_term_alter_employee_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='about/'),
        ),
    ]
